/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { X, Download, GraduationCap, Briefcase, Award, Code2, Mail, ExternalLink, MapPin, CheckCircle2 } from 'lucide-react';
import { PERSONAL_BRAND, VERIFIED_EDUCATION, VERIFIED_EXPERIENCE, SKILL_CATEGORIES } from '../data/portfolioData';

interface CvModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const CvModal: React.FC<CvModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  const handleDownload = () => {
    const element = window.document.createElement('a');
    const content = `# CURRICULUM VITAE — MEMOONA NAWAZ
Mathematics Educator | AI Evaluation Specialist | Visual Learning Creator
Email: ${PERSONAL_BRAND.email}
GitHub: ${PERSONAL_BRAND.github}
Location: ${PERSONAL_BRAND.location}

==================================================
1. EXECUTIVE SUMMARY
==================================================
Mathematician and educator with 6+ years of specialized instructional tenure across Cambridge O/A Level (4024, 9709 P1/P3), IGCSE (0580), and Digital SAT mathematics. AI Evaluation Specialist with Mindrift and Turing Company, validating symbolic multi-step reasoning trajectories and engineering quantitative benchmarks for frontier LLMs. Founder of Phantom Monaxa, dedicated to programmatic mathematical animations using Python and Manim.

==================================================
2. VERIFIED EDUCATION
==================================================
- M.Phil Mathematics (2026)
  University of Central Punjab | Starting Soon / Admission Pending
  Field: Pure & Applied Mathematics

- BS Mathematics (ADP) (2022–2024)
  University of the Punjab | CGPA: 2.9 / 4.00
  Field: Pure & Computational Mathematics

- BSc Double Mathematics & Physics (2020–2022)
  University of the Punjab | Marks: 61.8%
  Field: Double Mathematics & Physics

- FSc Pre-Engineering
  BISE Gujranwala | Marks: 72.45%

- SSC Bio Science
  BISE Gujranwala | Marks: 82.17%

==================================================
3. PROFESSIONAL EXPERIENCE
==================================================
1. Mathematics Consultant & Tutor (2020–Present)
   - Comprehensive private and institutional tutoring for Cambridge O/A Level, IGCSE & SAT candidates.
   - Formulating step-by-step diagnostic workflows and visual reasoning frameworks.

2. AI Logic Optimization & Mathematical Validation — Mindrift
   - Evaluating multi-step mathematical solutions and symbolic reasoning generated by LLMs.
   - Identifying edge-case algorithmic errors, symbolic inaccuracies, and logical fallacies.

3. AI Benchmark Developer — Turing Company
   - Developing high-difficulty mathematical benchmark datasets and test suites for AI systems.
   - Engineering automated grading criteria and structured multi-step reasoning rubrics.

4. O/A Level Mathematics Teacher — Beaconhouse
   - Cambridge O-Level and A-Level Pure Mathematics 3 (9709) faculty.
   - Developing modular differentiation, integration, and trigonometric identities practice sets.

5. IGCSE Mathematics Teacher — School of Enablers
   - Cambridge IGCSE Mathematics syllabus (Core & Extended) instruction.
   - Creating visual explanations for algebra, transformations, and probability trees.

6. O-Level Mathematics Teacher — LGS (Lahore Grammar School)
   - Cambridge O-Level (4024) faculty.
   - Moderating mock exams and coordinating syllabus progression.

==================================================
4. CORE SKILLS & TOOLKIT
==================================================
- Mathematics: Pure Mathematics, Calculus, Complex Analysis, Linear Algebra, SAT Math
- Programming: Python, HTML, CSS, JavaScript, LaTeX
- Visualization: Manim (3Blue1Brown Animation Library), Parametric Geometry
- AI Validation: Benchmark Development, Logic Optimization, Proof Verification
- Pedagogy: Cambridge Board Criteria, Diagnostic Assessment, Examiner Alignment

© 2026 Memoona Nawaz. All Rights Reserved.`;

    const file = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = 'Memoona-Nawaz-CV.md';
    window.document.body.appendChild(element);
    element.click();
    window.document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto bg-black/85 backdrop-blur-md">
      <div 
        className="relative w-full max-w-4xl bg-[#0F1110] border border-neutral-800 rounded-2xl shadow-2xl overflow-hidden my-8"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Top Header Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-neutral-800 bg-[#0B0D0C]/90">
          <div className="flex items-center gap-3">
            <span className="font-mono text-xs font-bold text-emerald-400 bg-emerald-950/70 px-2 py-0.5 rounded border border-emerald-800/40">
              OFFICIAL CV
            </span>
            <span className="text-xs font-mono text-neutral-400">
              MEMOONA NAWAZ
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono font-medium text-neutral-200 bg-neutral-900 hover:bg-neutral-800 border border-neutral-700 rounded-lg transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-emerald-400" />
              <span>Download</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-neutral-400 hover:text-white hover:bg-neutral-800 transition-colors"
              aria-label="Close CV modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-6 sm:p-10 space-y-10 max-h-[80vh] overflow-y-auto font-sans">
          
          {/* Header Contact Block */}
          <div className="border-b border-neutral-800 pb-8">
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-2">
              {PERSONAL_BRAND.name}
            </h2>
            <div className="text-sm font-mono text-emerald-400 font-semibold mb-4">
              {PERSONAL_BRAND.headline}
            </div>

            <div className="flex flex-wrap items-center gap-y-2 gap-x-6 text-xs font-mono text-neutral-400">
              <span className="flex items-center gap-1.5 text-neutral-300">
                <Mail className="w-3.5 h-3.5 text-emerald-400" />
                <span>{PERSONAL_BRAND.email}</span>
              </span>
              <span className="flex items-center gap-1.5 text-neutral-300">
                <MapPin className="w-3.5 h-3.5 text-emerald-400" />
                <span>{PERSONAL_BRAND.location}</span>
              </span>
              <span className="flex items-center gap-1.5 text-neutral-300">
                <ExternalLink className="w-3.5 h-3.5 text-emerald-400" />
                <span>github.com/memoonanawaz</span>
              </span>
            </div>
          </div>

          {/* Section: Professional Summary */}
          <div>
            <h3 className="text-xs font-mono uppercase tracking-widest text-emerald-400 font-bold mb-3 flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
              <span>PROFESSIONAL SUMMARY</span>
            </h3>
            <p className="text-sm text-neutral-300 leading-relaxed bg-[#0B0D0C] p-5 rounded-xl border border-neutral-800">
              Accomplished mathematician, Cambridge O/A Level educator, and AI evaluation specialist with 6+ years of instructional experience. Specialized in Pure Mathematics 3 (calculus, differential equations), visual problem-solving frameworks via Python and Manim, and frontier AI reasoning evaluation at Mindrift and Turing Company.
            </p>
          </div>

          {/* Section: Verified Education */}
          <div>
            <h3 className="text-xs font-mono uppercase tracking-widest text-emerald-400 font-bold mb-4 flex items-center gap-2">
              <GraduationCap className="w-4 h-4 text-emerald-400" />
              <span>VERIFIED ACADEMIC QUALIFICATIONS</span>
            </h3>

            <div className="space-y-4">
              {VERIFIED_EDUCATION.map((edu, idx) => (
                <div key={idx} className="bg-[#0B0D0C] p-5 rounded-xl border border-neutral-800">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-2">
                    <h4 className="text-base font-bold text-white font-display">
                      {edu.degree}
                    </h4>
                    <span className="text-xs font-mono text-emerald-400 font-semibold">
                      {edu.year}
                    </span>
                  </div>
                  <div className="text-xs text-neutral-400 font-medium mb-2">
                    {edu.institution} · <span className="text-neutral-300">{edu.field}</span>
                  </div>
                  <div className="text-xs font-mono text-emerald-500 font-medium">
                    {edu.score}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section: Professional Experience */}
          <div>
            <h3 className="text-xs font-mono uppercase tracking-widest text-emerald-400 font-bold mb-4 flex items-center gap-2">
              <Briefcase className="w-4 h-4 text-emerald-400" />
              <span>PROFESSIONAL TENURE & ROLES</span>
            </h3>

            <div className="space-y-4">
              {VERIFIED_EXPERIENCE.map((exp, idx) => (
                <div key={idx} className="bg-[#0B0D0C] p-5 rounded-xl border border-neutral-800">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-1">
                    <h4 className="text-base font-bold text-white font-display">
                      {exp.role}
                    </h4>
                    <span className="text-xs font-mono text-emerald-400 font-medium">
                      {exp.duration}
                    </span>
                  </div>
                  <div className="text-xs text-neutral-400 font-medium mb-3">
                    {exp.organization} {exp.location ? `· ${exp.location}` : ''}
                  </div>
                  <ul className="space-y-1.5 text-xs text-neutral-300">
                    {exp.responsibilities.map((resp, rIdx) => (
                      <li key={rIdx} className="flex items-start gap-2">
                        <span className="text-emerald-400 mt-0.5">•</span>
                        <span>{resp}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* Section: Core Skills */}
          <div>
            <h3 className="text-xs font-mono uppercase tracking-widest text-emerald-400 font-bold mb-4 flex items-center gap-2">
              <Code2 className="w-4 h-4 text-emerald-400" />
              <span>TECHNICAL & PEDAGOGICAL TOOLKIT</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {SKILL_CATEGORIES.map((cat, idx) => (
                <div key={idx} className="bg-[#0B0D0C] p-4 rounded-xl border border-neutral-800">
                  <div className="text-xs font-mono font-bold text-white mb-2">
                    {cat.category}
                  </div>
                  <div className="text-xs text-neutral-400 leading-relaxed">
                    {cat.skills.join(', ')}
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Modal Bottom Actions */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-neutral-800 bg-[#0B0D0C]/90">
          <div className="text-xs font-mono text-neutral-500">
            Source: Verified CV Documentation (2026)
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-5 py-2 text-xs font-semibold text-neutral-950 bg-emerald-400 hover:bg-emerald-300 rounded-lg transition-colors shadow-md"
            >
              <Download className="w-4 h-4" />
              <span>Download CV (.MD)</span>
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 text-xs font-medium text-neutral-400 hover:text-white bg-neutral-900 rounded-lg transition-colors"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
